---
dependency:
  name: galaxy
  requirements_file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: base-ant-centos
    image: centos:7
    privileged: true
  - name: base-ant-ubuntu
    image: ubuntu:bionic
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
