---
dependency:
  name: galaxy
  requirements_file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: base-ant-centos8
    image: quay.io/centos/centos:stream8
    privileged: true
  - name: base-ant-centos7
    image: centos:7
    privileged: true
  - name: base-maven-focal
    image: ubuntu:focal
    privileged: true
  - name: base-ant-ubuntu
    image: ubuntu:bionic
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
